/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NapiNftResult {
  files: Array<RcStr>
  issues: Array<RcStr>
}

export declare function nodeFileTrace(
  projectRoot: RcStr,
  cwd: RcStr,
  outputBase: RcStr,
  input: Array<string>,
  graph: boolean,
  showIssues: boolean,
  maxDepth?: number | undefined | null
): Promise<NapiNftResult>
