[package]
name = "turbopack-module-federation"
version = "0.1.0"
description = "Module Federation support for Turbopack"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = "0.21.0"
indoc = { workspace = true }
serde_json = { workspace = true }

turbo-rcstr = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-fs = { workspace = true }
turbo-tasks-hash = { workspace = true }
turbopack-core = { workspace = true }
turbopack-ecmascript = { workspace = true }
