/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NapiExperimentalConfig {
  esmExternals?: string | boolean
}

export interface NapiNextConfigComplete {
  experimental: NapiExperimentalConfig
  bundlePagesRouterDependencies?: boolean
}

export interface NapiNextExternalsPluginOptions {
  compilerType: string
  config: NapiNextConfigComplete
  optOutBundlingPackageRegex: RegExp
  finalTranspilePackages: Array<string>
  dir: string
  defaultOverrides: Record<string, string>
}

export declare function registerNextExternalsPlugin(): void
