//@ts-check

const { composePlugins, withNx } = require('@nx/next')

// Nx loads this nested config instead of the root config generated by the deploy
// test harness, so translate its deployment-safe feature flags here as well.
if (process.env.NEXT_PRIVATE_EXPERIMENTAL_CACHE_COMPONENTS) {
  process.env.__NEXT_CACHE_COMPONENTS =
    process.env.NEXT_PRIVATE_EXPERIMENTAL_CACHE_COMPONENTS
}
if (process.env.NEXT_PRIVATE_EXPERIMENTAL_CACHED_NAVIGATIONS) {
  process.env.__NEXT_EXPERIMENTAL_CACHED_NAVIGATIONS =
    process.env.NEXT_PRIVATE_EXPERIMENTAL_CACHED_NAVIGATIONS
}

/**
 * @type {import('@nx/next/plugins/with-nx').WithNxOptions}
 **/
const nextConfig = {
  // Use this to set Nx-specific options
  // See: https://nx.dev/recipes/next/next-config-setup
  nx: {},
}

const plugins = [
  // Add more Next.js plugins to this list if needed.
  withNx,
]

module.exports = composePlugins(...plugins)(nextConfig)
