# Shared by CI (via $include) and local docker builds (via npx mmm-matrix)
target:
  $dynamic: "`${this.arch}-${this.vendor}-${this.sys}${this.abi ? '-' + this.abi : ''}`"
build_task: build-native-release
os:
  mac:
    host: "['self-hosted', 'macos', 'arm64']"
    arch: [x86_64, aarch64]
    vendor: apple
    sys: darwin
  windows:
    host: "['self-hosted', 'windows', 'x64']"
    vendor: pc
    sys: windows
    abi: msvc
    arch:
      x86_64: {}
      aarch64:
        build_task: build-native-no-plugin-release
  linux:
    host: "['self-hosted', 'linux', 'x64', 'metal']"
    docker: next-swc-builder:latest
    vendor: unknown
    sys: linux
    abi:
      gnu:
        arch: [x86_64, aarch64]
      musl:
        arch: [x86_64, aarch64]
