packages:
  - 'actions/*'
injectWorkspacePackages: true
minimumReleaseAge: 2880 # 48 hrs
minimumReleaseAgeExclude:
  - react
  - react-dom
  - '@next/*'
  - 'next'
  - '@turbo/*'
  - 'turbo'
  - '@vercel/*'
  - '@workflow/*'
