;[
  'package.json',
  'test/unit/module-register/hook.mjs',
  'test/unit/module-register/hook2.mjs',
  'test/unit/module-register/hook3.mjs',
  'test/unit/module-register/input-esm.mjs',
  'test/unit/module-register/input.js',
  'test/unit/module-register/node_modules/test-pkg/index.mjs',
  'test/unit/module-register/node_modules/test-pkg/package.json',
]
