repo = "next.js"
name = "mmastrac__slash__associated-tuples"
branch = "mmastrac/associated-tuples"
path = "/Users/matt/Library/Application Support/clydra/__slash__Users__slash__matt__slash__Documents__slash__github__slash__vercel.toml/worktrees/next.js/mmastrac__slash__associated-tuples"
terminals = 1
