packages:
  - 'apps/*'
  - 'packages/*'
  - 'bench/*'
  - 'crates/*/js'
  - 'turbopack/crates/*/js'
  - 'turbopack/crates/turbopack-tests/tests/execution'
  - 'turbopack/packages/*'
updateNotifier: false
publicHoistPattern:
  - '*eslint*'
allowBuilds:
  '@ast-grep/cli': true
ignoredBuiltDependencies:
  - '@datadog/native-appsec'
  - '@datadog/native-metrics'
  - '@datadog/pprof'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - cpu-features
  - dd-trace
  - esbuild
  - msw
  - nx
  - playwright-chromium
  - protobufjs
  - sharp
  - ssh2
  - unrs-resolver
  - wasm-pack
blockExoticSubdeps: true
minimumReleaseAge: 2880 # 48 hrs
minimumReleaseAgeExclude:
  - '@next/*'
  - '@turbo/*'
  - '@vercel/*'
  - '@workflow/*'
  - babel-plugin-react-compiler
  - next
  - react
  - react-dom
  - react-dom-*
  - react-experimental-builtin
  - react-is
  - react-is-builtin
  - react-server-dom-*
  - scheduler-*
  - turbo
