;[
  'package.json',
  'test/unit/pkg-project-root-mixed-directory/app-config.js',
  'test/unit/pkg-project-root-mixed-directory/input.js',
  'test/unit/pkg-project-root-mixed-directory/node_modules/some-pkg/app-config.js',
  'test/unit/pkg-project-root-mixed-directory/node_modules/some-pkg/index.js',
  'test/unit/pkg-project-root-mixed-directory/node_modules/some-pkg/package.json',
  'test/unit/pkg-project-root-mixed-directory/node_modules/some-pkg/local-asset.txt',
]
