# Each build is a plugin that only accepts its own config via defined features
#
# To rebuild:
#
#   for p in a b c; do
#     RUSTFLAGS= cargo build --target wasm32-wasip1 --release --features $p &&
#       cp target/wasm32-wasip1/release/swc_plugin_config_check.wasm ../fixture/swc_plugin_config_check_$p.wasm
#   done

[package]
name = "swc-plugin-config-check"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
a = []
b = []
c = []

[profile.release]
strip = "debuginfo"
codegen-units = 1
lto = true
opt-level = "z"

[dependencies]
serde = { version = "1.0.173", features = ["derive"] }
serde_json = "1.0.103"
swc_core = { version = "77", features = ["ecma_plugin_transform"] }

[workspace]
