// flow-typed signature: 5c815d97bc322b44aa30656fc2619bb0
// flow-typed version: <<STUB>>/react-loadable_v5.x/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loadable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loadable/babel' {
  declare module.exports: any;
}

declare module 'react-loadable/lib/babel' {
  declare module.exports: any;
}

declare module 'react-loadable/lib/index' {
  declare module.exports: any;
}

declare module 'react-loadable/lib/webpack' {
  declare module.exports: any;
}

declare module 'react-loadable/webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loadable/babel.js' {
  declare module.exports: $Exports<'react-loadable/babel'>;
}
declare module 'react-loadable/lib/babel.js' {
  declare module.exports: $Exports<'react-loadable/lib/babel'>;
}
declare module 'react-loadable/lib/index.js' {
  declare module.exports: $Exports<'react-loadable/lib/index'>;
}
declare module 'react-loadable/lib/webpack.js' {
  declare module.exports: $Exports<'react-loadable/lib/webpack'>;
}
declare module 'react-loadable/webpack.js' {
  declare module.exports: $Exports<'react-loadable/webpack'>;
}
