// flow-typed signature: d41ce38862b325831cb20e57893195bc
// flow-typed version: <<STUB>>/webpack-sources_v1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-sources'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-sources' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-sources/lib/CachedSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/ConcatSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/LineToLineMappedSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/OriginalSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/PrefixSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/RawSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/ReplaceSource' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/Source' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/SourceAndMapMixin' {
  declare module.exports: any;
}

declare module 'webpack-sources/lib/SourceMapSource' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-sources/lib/CachedSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/CachedSource'>;
}
declare module 'webpack-sources/lib/ConcatSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/ConcatSource'>;
}
declare module 'webpack-sources/lib/index.js' {
  declare module.exports: $Exports<'webpack-sources/lib/index'>;
}
declare module 'webpack-sources/lib/LineToLineMappedSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/LineToLineMappedSource'>;
}
declare module 'webpack-sources/lib/OriginalSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/OriginalSource'>;
}
declare module 'webpack-sources/lib/PrefixSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/PrefixSource'>;
}
declare module 'webpack-sources/lib/RawSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/RawSource'>;
}
declare module 'webpack-sources/lib/ReplaceSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/ReplaceSource'>;
}
declare module 'webpack-sources/lib/Source.js' {
  declare module.exports: $Exports<'webpack-sources/lib/Source'>;
}
declare module 'webpack-sources/lib/SourceAndMapMixin.js' {
  declare module.exports: $Exports<'webpack-sources/lib/SourceAndMapMixin'>;
}
declare module 'webpack-sources/lib/SourceMapSource.js' {
  declare module.exports: $Exports<'webpack-sources/lib/SourceMapSource'>;
}
