services:
  nextjs-standalone:
    build:
      context: .
      dockerfile: Dockerfile
    image: nextjs-standalone-image
    container_name: nextjs-standalone-container
    environment:
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3000:3000"
    restart: unless-stopped
