[package]
name = "turbopack-css"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
indoc = { workspace = true }
lightningcss = { workspace = true }
parcel_selectors = { workspace = true }
parcel_sourcemap = "2.1.1"
rustc-hash = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
swc_core = { workspace = true, features = [
  "ecma_ast",
  "common",
  "common_concurrent",
] }
tracing = { workspace = true }
turbo-bincode = { workspace = true }
turbo-rcstr = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }
turbo-tasks-fs = { path = "../turbo-tasks-fs", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }
turbopack-ecmascript = { path = "../turbopack-ecmascript", default-features = false }
urlencoding = { workspace = true }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime", "turbo-tasks-fs/tokio_runtime", "turbopack-core/tokio_runtime", "turbopack-ecmascript/tokio_runtime"]
sync = ["turbo-tasks/sync", "turbo-tasks-fs/sync", "turbopack-core/sync", "turbopack-ecmascript/sync"]

