[package]
name = "next-taskr"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = "0.21.0"
clap = { workspace = true }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }
turbo-rcstr = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-backend = { workspace = true }
turbo-tasks-fs = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
