/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NapiNftResult {
  files: Array<RcStr>
  issues: Array<RcStr>
}
export declare function nodeFileTrace(projectRoot: RcStr, cwd: RcStr, outputBase: RcStr, input: Array<string>, graph: boolean, showIssues: boolean, maxDepth?: number | undefined | null): Promise<NapiNftResult>
