[package]
name = "turbo-tasks-bytes"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime"]
sync = ["turbo-tasks/sync"]
