[package]
name = "turbopack-lightningcss-napi"
version = "0.0.0"
edition = "2021"
publish = false
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
cssparser = "0.33.0"
lightningcss = { workspace = true, features = ["nodejs", "serde", "visitor"] }
napi = { workspace = true }
parcel_sourcemap = { version = "2.1.1", features = ["json"] }
serde = { workspace = true }
serde-content = { version = "0.1.2", features = ["serde"] }
serde-detach = "0.0.1"
serde_bytes = "0.11.5"
smallvec = { workspace = true }
