[package]
name = "turbopack-test-utils"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
regex = { workspace = true, features = ["pattern"] }
serde = { workspace = true }
similar = "2.2.0"
turbo-rcstr = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }
turbo-tasks-fs = { path = "../turbo-tasks-fs", default-features = false }
turbo-tasks-hash = { workspace = true }
turbopack-cli-utils = { path = "../turbopack-cli-utils", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }
rustc-hash = { workspace = true }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime", "turbo-tasks-fs/tokio_runtime", "turbopack-cli-utils/tokio_runtime", "turbopack-core/tokio_runtime"]
sync = ["turbo-tasks/sync", "turbo-tasks-fs/sync", "turbopack-cli-utils/sync", "turbopack-core/sync"]

