[package]
name = "turbopack-tracing"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[features]
test_persistent_cache = []
bench_against_node_nft = []
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime", "turbo-tasks-backend/tokio_runtime", "turbo-tasks-fs/tokio_runtime", "turbopack/tokio_runtime", "turbopack-core/tokio_runtime", "turbopack-ecmascript/tokio_runtime", "turbopack-node/tokio_runtime", "turbopack-resolve/tokio_runtime"]
sync = ["turbo-tasks/sync", "turbo-tasks-backend/sync", "turbo-tasks-fs/sync", "turbopack/sync", "turbopack-core/sync", "turbopack-ecmascript/sync", "turbopack-node/sync", "turbopack-resolve/sync"]

[lints]
workspace = true

[dependencies]
turbopack = { path = "../turbopack", default-features = false }

[dev-dependencies]
anyhow = { workspace = true }
rustc-hash = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

turbo-rcstr = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }
turbo-tasks-fs = { path = "../turbo-tasks-fs", default-features = false }
turbo-tasks-malloc = { workspace = true, default-features = false }
turbo-tasks-backend = { path = "../turbo-tasks-backend", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }
turbopack-resolve = { path = "../turbopack-resolve", default-features = false }
turbopack-ecmascript = { path = "../turbopack-ecmascript", default-features = false }
turbopack-node = { path = "../turbopack-node", default-features = false, features = ["process_pool"]}

criterion = { workspace = true, features = ["async_tokio"] }
difference = "2.0"
similar = "2.2.0"
rstest = { workspace = true }
rstest_reuse = "0.5.0"
tokio = { workspace = true }


[[bench]]
name = "mod"
harness = false
