[package]
name = "turbopack-ecmascript-hmr-protocol"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

turbo-rcstr = { workspace = true }
turbopack-cli-utils = { path = "../turbopack-cli-utils", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbopack-cli-utils/tokio_runtime", "turbopack-core/tokio_runtime"]
sync = ["turbopack-cli-utils/sync", "turbopack-core/sync"]
