[package]
name = "next-build"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
next-core = { path = "../next-core", default-features = false }
turbopack-core = { path = "../../turbopack/crates/turbopack-core", default-features = false }
turbo-rcstr = { workspace = true }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["next-core/tokio_runtime", "turbopack-core/tokio_runtime"]
sync = ["next-core/sync", "turbopack-core/sync"]

