[package]
name = "turbo-tasks-fetch"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
quick_cache = { workspace = true }
reqwest = { workspace = true, features = ["rustls"] }
serde = { workspace = true }
tokio = { workspace = true }
turbo-rcstr = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-fs = { workspace = true }
turbopack-core = { workspace = true }

[dev-dependencies]
mockito = { version = "1.7.0", default-features = false }
tokio = { workspace = true, features = ["full"] }
turbo-tasks-testing = { workspace = true }
turbo-tasks-backend = { workspace = true }

