[package]
name = "turbopack-rn"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"

[features]
default = ["custom_allocator"]
serializable = []
tokio_console = [
  "dep:console-subscriber",
  "tokio/tracing",
  "turbo-tasks/tokio_tracing",
]
profile = []
custom_allocator = ["turbo-tasks-malloc/custom_allocator"]

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
async-trait = { workspace = true }
bincode = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
console-subscriber = { workspace = true, optional = true }
dunce = { workspace = true }
futures = { workspace = true }
owo-colors = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
swc_core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["json"] }
turbo-rcstr = { workspace = true }
turbo-tasks = { workspace = true }
turbo-tasks-backend = { workspace = true }
turbo-tasks-env = { workspace = true }
turbo-unix-path = { workspace = true }
turbo-tasks-hash = { workspace = true }
turbo-tasks-fs = { workspace = true }
turbo-tasks-malloc = { workspace = true, default-features = false }
turbopack = { workspace = true }
turbopack-browser = { workspace = true }
turbopack-cli-utils = { workspace = true }
turbopack-core = { workspace = true }
turbopack-css = { workspace = true }
turbopack-dev-server = { workspace = true }
turbopack-ecmascript = { workspace = true }
turbopack-ecmascript-plugins = { workspace = true, features = [
  "transform_emotion",
] }
turbopack-ecmascript-runtime = { workspace = true }
turbopack-ecmascript-hmr-protocol = { workspace = true }
turbopack-env = { workspace = true }
turbopack-image = { workspace = true, features = ["webp"] }
turbopack-node = { workspace = true, default-features = false, features = ["process_pool"]}
turbopack-nodejs = { workspace = true }
turbopack-resolve = { workspace = true }
turbopack-static = { workspace = true }
turbopack-trace-utils = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
urlencoding = { workspace = true }
webbrowser = { workspace = true }

turbo-esregex = { workspace = true }
hyper = { version = "1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
serde_qs = { workspace = true }
serde_json = { workspace = true }
tokio-util = { workspace = true }
hyper-tungstenite = "0.18.0"
pin-project-lite = { workspace = true }
either = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio"] }
regex = { workspace = true }
turbopack-bench = { workspace = true }
turbo-tasks-malloc = { workspace = true, features = ["custom_allocator"] }

[build-dependencies]
anyhow = { workspace = true }
vergen-gitcl = { workspace = true }
