import type { Metadata } from 'next'

export const generateMetadata = async ({ params }): Promise<Metadata> => {
  const { slug } = await params
  return { title: `${slug}` }
}

export default function Page() {
  return (
    <>
      <p>{'BEGINNINGasdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'MIDDLEasdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'asdasdasadasdasd232344234234234'}</p>
      <p>{'asdsadiasdhasuidhasdiuasasdsadduhiuihueiohjewiohjewiohj'}</p>
      <p>{'asdasd'}</p>
      <p>{'ENDasdasdasadasdasd232344234234234'}</p>
    </>
  )
}
