// flow-typed signature: 6efcfad8e6dad5d1ef55854d4f6d2272
// flow-typed version: <<STUB>>/autodll-webpack-plugin_v0.4.2/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autodll-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autodll-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autodll-webpack-plugin/lib/createCompileIfNeeded' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createConfig' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createHandleStats' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createHash' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createLogger' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createMemory' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createSettings' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/getEnv' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/getInstanceIndex' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/mapParentConfig' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/normalizeEntry' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/paths' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/utils/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/utils/safeClone' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/validateCache' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createCompileIfNeeded' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createConfig' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createHandleStats' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createHash' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createLogger' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createMemory' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createSettings' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/getEnv' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/getInstanceIndex' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/mapParentConfig' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/normalizeEntry' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/paths' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/plugin' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/utils/fs' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/utils/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/utils/safeClone' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/validateCache' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autodll-webpack-plugin/lib/createCompileIfNeeded.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createCompileIfNeeded'>;
}
declare module 'autodll-webpack-plugin/lib/createConfig.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createConfig'>;
}
declare module 'autodll-webpack-plugin/lib/createHandleStats.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createHandleStats'>;
}
declare module 'autodll-webpack-plugin/lib/createHash.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createHash'>;
}
declare module 'autodll-webpack-plugin/lib/createLogger.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createLogger'>;
}
declare module 'autodll-webpack-plugin/lib/createMemory.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createMemory'>;
}
declare module 'autodll-webpack-plugin/lib/createSettings.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createSettings'>;
}
declare module 'autodll-webpack-plugin/lib/getEnv.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/getEnv'>;
}
declare module 'autodll-webpack-plugin/lib/getInstanceIndex.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/getInstanceIndex'>;
}
declare module 'autodll-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/index'>;
}
declare module 'autodll-webpack-plugin/lib/mapParentConfig.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/mapParentConfig'>;
}
declare module 'autodll-webpack-plugin/lib/normalizeEntry.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/normalizeEntry'>;
}
declare module 'autodll-webpack-plugin/lib/paths.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/paths'>;
}
declare module 'autodll-webpack-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/plugin'>;
}
declare module 'autodll-webpack-plugin/lib/utils/fs.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/utils/fs'>;
}
declare module 'autodll-webpack-plugin/lib/utils/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/utils/index'>;
}
declare module 'autodll-webpack-plugin/lib/utils/safeClone.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/utils/safeClone'>;
}
declare module 'autodll-webpack-plugin/lib/validateCache.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/validateCache'>;
}
declare module 'autodll-webpack-plugin/src/createCompileIfNeeded.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createCompileIfNeeded'>;
}
declare module 'autodll-webpack-plugin/src/createConfig.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createConfig'>;
}
declare module 'autodll-webpack-plugin/src/createHandleStats.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createHandleStats'>;
}
declare module 'autodll-webpack-plugin/src/createHash.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createHash'>;
}
declare module 'autodll-webpack-plugin/src/createLogger.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createLogger'>;
}
declare module 'autodll-webpack-plugin/src/createMemory.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createMemory'>;
}
declare module 'autodll-webpack-plugin/src/createSettings.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createSettings'>;
}
declare module 'autodll-webpack-plugin/src/getEnv.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/getEnv'>;
}
declare module 'autodll-webpack-plugin/src/getInstanceIndex.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/getInstanceIndex'>;
}
declare module 'autodll-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/index'>;
}
declare module 'autodll-webpack-plugin/src/mapParentConfig.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/mapParentConfig'>;
}
declare module 'autodll-webpack-plugin/src/normalizeEntry.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/normalizeEntry'>;
}
declare module 'autodll-webpack-plugin/src/paths.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/paths'>;
}
declare module 'autodll-webpack-plugin/src/plugin.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/plugin'>;
}
declare module 'autodll-webpack-plugin/src/utils/fs.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/utils/fs'>;
}
declare module 'autodll-webpack-plugin/src/utils/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/utils/index'>;
}
declare module 'autodll-webpack-plugin/src/utils/safeClone.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/utils/safeClone'>;
}
declare module 'autodll-webpack-plugin/src/validateCache.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/validateCache'>;
}
