[package]
name = "next-core"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = "0.21.0"
allsorts = { workspace = true }
bincode = { workspace = true }
either = { workspace = true, features = ["serde"] }
futures = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
indoc = { workspace = true }
itertools = { workspace = true }
lightningcss = { workspace = true }
mime_guess = "2.0.4"
percent-encoding = "2.3.1"
phf = { workspace = true }
qstring = { workspace = true }
react_remove_properties = { workspace = true }
regex = { workspace = true }
regress = { workspace = true }
remove_console = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
smallvec = { workspace = true }
swc_sourcemap = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

swc_core = { workspace = true, features = [
  "base",
  "common_concurrent",
  "ecma_ast",
  "ecma_loader_lru",
  "ecma_loader_node",
  "ecma_minifier",
  "ecma_parser",
  "ecma_parser_typescript",
  "ecma_preset_env",
  "ecma_transforms",
  "ecma_transforms_optimization",
  "ecma_transforms_react",
  "ecma_transforms_typescript",
  "ecma_utils",
  "ecma_visit",
] }
modularize_imports = { workspace = true }

next-custom-transforms = { workspace = true }
next-taskless = { workspace = true }

turbo-bincode = { workspace = true }
turbo-rcstr = { workspace = true }
turbo-esregex = { path = "../../turbopack/crates/turbo-esregex", default-features = false }
turbo-tasks = { path = "../../turbopack/crates/turbo-tasks", default-features = false }
turbo-tasks-bytes = { path = "../../turbopack/crates/turbo-tasks-bytes", default-features = false }
turbo-tasks-env = { path = "../../turbopack/crates/turbo-tasks-env", default-features = false }
turbo-tasks-fetch = { path = "../../turbopack/crates/turbo-tasks-fetch", default-features = false }
turbo-tasks-fs = { path = "../../turbopack/crates/turbo-tasks-fs", default-features = false }
turbo-tasks-hash = { workspace = true }
turbopack = { path = "../../turbopack/crates/turbopack", default-features = false }
turbopack-browser = { path = "../../turbopack/crates/turbopack-browser", default-features = false }
turbopack-core = { path = "../../turbopack/crates/turbopack-core", default-features = false }
turbopack-css = { path = "../../turbopack/crates/turbopack-css", default-features = false }
turbopack-ecmascript = { path = "../../turbopack/crates/turbopack-ecmascript", default-features = false }
turbopack-ecmascript-plugins = { path = "../../turbopack/crates/turbopack-ecmascript-plugins", default-features = false, features = [
  "transform_emotion",
] }
turbopack-ecmascript-runtime = { path = "../../turbopack/crates/turbopack-ecmascript-runtime", default-features = false }
turbopack-image = { path = "../../turbopack/crates/turbopack-image", default-features = false }
turbopack-node = { path = "../../turbopack/crates/turbopack-node", default-features = false }
turbopack-nodejs = { path = "../../turbopack/crates/turbopack-nodejs", default-features = false }
turbopack-resolve = { path = "../../turbopack/crates/turbopack-resolve", default-features = false }
turbopack-static = { path = "../../turbopack/crates/turbopack-static", default-features = false }
turbopack-trace-utils = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
turbo-tasks-backend = { path = "../../turbopack/crates/turbo-tasks-backend", default-features = false }

[features]
default = ["tokio_runtime", "process_pool"]
process_pool = ["turbopack-node/process_pool"]
worker_pool = ["turbopack-node/worker_pool"]
next-font-local = []
image-webp = ["turbopack-image/webp"]
image-avif = ["turbopack-image/avif"]

# enable "HMR" for embedded assets
dynamic_embed_contents = [
  "turbo-tasks-fs/dynamic_embed_contents",
  "turbopack-browser/dynamic_embed_contents",
]
tokio_runtime = ["turbo-esregex/tokio_runtime", "turbo-tasks/tokio_runtime", "turbo-tasks-backend/tokio_runtime", "turbo-tasks-bytes/tokio_runtime", "turbo-tasks-env/tokio_runtime", "turbo-tasks-fetch/tokio_runtime", "turbo-tasks-fs/tokio_runtime", "turbopack/tokio_runtime", "turbopack-browser/tokio_runtime", "turbopack-core/tokio_runtime", "turbopack-css/tokio_runtime", "turbopack-ecmascript/tokio_runtime", "turbopack-ecmascript-plugins/tokio_runtime", "turbopack-ecmascript-runtime/tokio_runtime", "turbopack-image/tokio_runtime", "turbopack-node/tokio_runtime", "turbopack-nodejs/tokio_runtime", "turbopack-resolve/tokio_runtime", "turbopack-static/tokio_runtime"]
sync = ["turbo-esregex/sync", "turbo-tasks/sync", "turbo-tasks-backend/sync", "turbo-tasks-bytes/sync", "turbo-tasks-env/sync", "turbo-tasks-fetch/sync", "turbo-tasks-fs/sync", "turbopack/sync", "turbopack-browser/sync", "turbopack-core/sync", "turbopack-css/sync", "turbopack-ecmascript/sync", "turbopack-ecmascript-plugins/sync", "turbopack-ecmascript-runtime/sync", "turbopack-image/sync", "turbopack-node/sync", "turbopack-nodejs/sync", "turbopack-resolve/sync", "turbopack-static/sync"]
