[package]
name = "swc_plugin_backend_napi"
edition = "2024"
version = "0.0.0"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
atomic-wait = "1.1.0"
once_cell = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true }
swc_plugin_runner = { version = "25.0.0", default-features = false }
