;[
  // 'node_modules/fs-extra/lib/copy/copy-sync.js',
  // 'node_modules/fs-extra/lib/copy/copy.js',
  // 'node_modules/fs-extra/lib/copy/index.js',
  // 'node_modules/fs-extra/lib/empty/index.js',
  // 'node_modules/fs-extra/lib/ensure/file.js',
  // 'node_modules/fs-extra/lib/ensure/index.js',
  // 'node_modules/fs-extra/lib/ensure/link.js',
  // 'node_modules/fs-extra/lib/ensure/symlink-paths.js',
  // 'node_modules/fs-extra/lib/ensure/symlink-type.js',
  // 'node_modules/fs-extra/lib/ensure/symlink.js',
  // 'node_modules/fs-extra/lib/fs/index.js',
  // 'node_modules/fs-extra/lib/index.js',
  // 'node_modules/fs-extra/lib/json/index.js',
  // 'node_modules/fs-extra/lib/json/jsonfile.js',
  // 'node_modules/fs-extra/lib/json/output-json-sync.js',
  // 'node_modules/fs-extra/lib/json/output-json.js',
  // 'node_modules/fs-extra/lib/mkdirs/index.js',
  // 'node_modules/fs-extra/lib/mkdirs/make-dir.js',
  // 'node_modules/fs-extra/lib/mkdirs/utils.js',
  // 'node_modules/fs-extra/lib/move/index.js',
  // 'node_modules/fs-extra/lib/move/move-sync.js',
  // 'node_modules/fs-extra/lib/move/move.js',
  // 'node_modules/fs-extra/lib/output-file/index.js',
  // 'node_modules/fs-extra/lib/path-exists/index.js',
  // 'node_modules/fs-extra/lib/remove/index.js',
  // 'node_modules/fs-extra/lib/remove/rimraf.js',
  // 'node_modules/fs-extra/lib/util/stat.js',
  // 'node_modules/fs-extra/lib/util/utimes.js',
  // 'node_modules/fs-extra/package.json',
  // 'node_modules/graceful-fs/clone.js',
  // 'node_modules/graceful-fs/graceful-fs.js',
  // 'node_modules/graceful-fs/legacy-streams.js',
  // 'node_modules/graceful-fs/package.json',
  // 'node_modules/graceful-fs/polyfills.js',
  // 'node_modules/jsonfile/index.js',
  // 'node_modules/jsonfile/package.json',
  // 'node_modules/jsonfile/utils.js',
  // 'node_modules/universalify/index.js',
  // 'node_modules/universalify/package.json',
  'package.json',
  'test/unit/asset-fs-extra/asset1.txt',
  'test/unit/asset-fs-extra/asset2.json',
  'test/unit/asset-fs-extra/input.js',
]
