/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Project name: Next.js Sample App
 * Environment: Production
 * Project Id: a7844231-064c-016c-1dad-38228cbc505d
 */
export const languages = {
  /**
   * Default project language
   */
  default: {
    codename: "default",
    id: "00000000-0000-0000-0000-000000000000",
    isActive: true,
    isDefault: true,
    fallbackLanguageId: "00000000-0000-0000-0000-000000000000",
    externalId: undefined,
    name: "Default project language",
  },
} as const;
