/**
 * Generated by '@kontent-ai/model-generator@5.9.0'
 *
 * Project name: Next.js Sample App
 * Environment: Production
 * Project Id: a7844231-064c-016c-1dad-38228cbc505d
 */
export const webhooks = {} as const;
