/**
 * @license React
 * react-server-dom-webpack-writer.browser.production.min.server.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
'use strict';var e=require("react"),l=null,m=0;function n(a,b){if(0!==b.length)if(512<b.length)0<m&&(a.enqueue(new Uint8Array(l.buffer,0,m)),l=new Uint8Array(512),m=0),a.enqueue(b);else{var d=l.length-m;d<b.length&&(0===d?a.enqueue(l):(l.set(b.subarray(0,d),m),a.enqueue(l),b=b.subarray(d)),l=new Uint8Array(512),m=0);l.set(b,m);m+=b.length}return!0}var p=new TextEncoder;function q(a){return p.encode(a)}function t(a,b){"function"===typeof a.error?a.error(b):a.close()}
var u=JSON.stringify,w=Symbol.for("react.module.reference"),x=Symbol.for("react.element"),aa=Symbol.for("react.fragment"),ba=Symbol.for("react.provider"),ca=Symbol.for("react.server_context"),da=Symbol.for("react.forward_ref"),ea=Symbol.for("react.memo"),y=Symbol.for("react.lazy"),fa=Symbol.for("react.default_value");
function z(a,b,d,c,f,g,h){this.acceptsBooleans=2===b||3===b||4===b;this.attributeName=c;this.attributeNamespace=f;this.mustUseProperty=d;this.propertyName=a;this.type=b;this.sanitizeURL=g;this.removeEmptyString=h}var ha="children dangerouslySetInnerHTML defaultValue defaultChecked innerHTML suppressContentEditableWarning suppressHydrationWarning style".split(" ");ha.push("innerText","textContent");ha.forEach(function(a){new z(a,0,!1,a,null,!1,!1)});
[["acceptCharset","accept-charset"],["className","class"],["htmlFor","for"],["httpEquiv","http-equiv"]].forEach(function(a){new z(a[0],1,!1,a[1],null,!1,!1)});["contentEditable","draggable","spellCheck","value"].forEach(function(a){new z(a,2,!1,a.toLowerCase(),null,!1,!1)});["autoReverse","externalResourcesRequired","focusable","preserveAlpha"].forEach(function(a){new z(a,2,!1,a,null,!1,!1)});
"allowFullScreen async autoFocus autoPlay controls default defer disabled disablePictureInPicture disableRemotePlayback formNoValidate hidden loop noModule noValidate open playsInline readOnly required reversed scoped seamless itemScope".split(" ").forEach(function(a){new z(a,3,!1,a.toLowerCase(),null,!1,!1)});["checked","multiple","muted","selected"].forEach(function(a){new z(a,3,!0,a,null,!1,!1)});["capture","download"].forEach(function(a){new z(a,4,!1,a,null,!1,!1)});
["cols","rows","size","span"].forEach(function(a){new z(a,6,!1,a,null,!1,!1)});["rowSpan","start"].forEach(function(a){new z(a,5,!1,a.toLowerCase(),null,!1,!1)});var B=/[\-:]([a-z])/g;function C(a){return a[1].toUpperCase()}
"accent-height alignment-baseline arabic-form baseline-shift cap-height clip-path clip-rule color-interpolation color-interpolation-filters color-profile color-rendering dominant-baseline enable-background fill-opacity fill-rule flood-color flood-opacity font-family font-size font-size-adjust font-stretch font-style font-variant font-weight glyph-name glyph-orientation-horizontal glyph-orientation-vertical horiz-adv-x horiz-origin-x image-rendering letter-spacing lighting-color marker-end marker-mid marker-start overline-position overline-thickness paint-order panose-1 pointer-events rendering-intent shape-rendering stop-color stop-opacity strikethrough-position strikethrough-thickness stroke-dasharray stroke-dashoffset stroke-linecap stroke-linejoin stroke-miterlimit stroke-opacity stroke-width text-anchor text-decoration text-rendering underline-position underline-thickness unicode-bidi unicode-range units-per-em v-alphabetic v-hanging v-ideographic v-mathematical vector-effect vert-adv-y vert-origin-x vert-origin-y word-spacing writing-mode xmlns:xlink x-height".split(" ").forEach(function(a){var b=a.replace(B,
C);new z(b,1,!1,a,null,!1,!1)});"xlink:actuate xlink:arcrole xlink:role xlink:show xlink:title xlink:type".split(" ").forEach(function(a){var b=a.replace(B,C);new z(b,1,!1,a,"http://www.w3.org/1999/xlink",!1,!1)});["xml:base","xml:lang","xml:space"].forEach(function(a){var b=a.replace(B,C);new z(b,1,!1,a,"http://www.w3.org/XML/1998/namespace",!1,!1)});["tabIndex","crossOrigin"].forEach(function(a){new z(a,1,!1,a.toLowerCase(),null,!1,!1)});
new z("xlinkHref",1,!1,"xlink:href","http://www.w3.org/1999/xlink",!0,!1);["src","href","action","formAction"].forEach(function(a){new z(a,1,!1,a.toLowerCase(),null,!0,!0)});
var D={animationIterationCount:!0,aspectRatio:!0,borderImageOutset:!0,borderImageSlice:!0,borderImageWidth:!0,boxFlex:!0,boxFlexGroup:!0,boxOrdinalGroup:!0,columnCount:!0,columns:!0,flex:!0,flexGrow:!0,flexPositive:!0,flexShrink:!0,flexNegative:!0,flexOrder:!0,gridArea:!0,gridRow:!0,gridRowEnd:!0,gridRowSpan:!0,gridRowStart:!0,gridColumn:!0,gridColumnEnd:!0,gridColumnSpan:!0,gridColumnStart:!0,fontWeight:!0,lineClamp:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,tabSize:!0,widows:!0,zIndex:!0,zoom:!0,
fillOpacity:!0,floodOpacity:!0,stopOpacity:!0,strokeDasharray:!0,strokeDashoffset:!0,strokeMiterlimit:!0,strokeOpacity:!0,strokeWidth:!0},ia=["Webkit","ms","Moz","O"];Object.keys(D).forEach(function(a){ia.forEach(function(b){b=b+a.charAt(0).toUpperCase()+a.substring(1);D[b]=D[a]})});var ja=Array.isArray;q("<script>");q("\x3c/script>");q('<script src="');q('<script type="module" src="');q('" integrity="');q('" async="">\x3c/script>');q("\x3c!-- --\x3e");q(' style="');q(":");q(";");q(" ");q('="');q('"');
q('=""');q(">");q("/>");q(' selected=""');q("\n");q("<!DOCTYPE html>");q("</");q(">");q('<template id="');q('"></template>');q("\x3c!--$--\x3e");q('\x3c!--$?--\x3e<template id="');q('"></template>');q("\x3c!--$!--\x3e");q("\x3c!--/$--\x3e");q("<template");q('"');q(' data-dgst="');q(' data-msg="');q(' data-stck="');q("></template>");q('<div hidden id="');q('">');q("</div>");q('<svg aria-hidden="true" style="display:none" id="');q('">');q("</svg>");q('<math aria-hidden="true" style="display:none" id="');
q('">');q("</math>");q('<table hidden id="');q('">');q("</table>");q('<table hidden><tbody id="');q('">');q("</tbody></table>");q('<table hidden><tr id="');q('">');q("</tr></table>");q('<table hidden><colgroup id="');q('">');q("</colgroup></table>");q('function $RS(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};$RS("');q('$RS("');q('","');q('")\x3c/script>');q('function $RC(a,b){a=document.getElementById(a);b=document.getElementById(b);b.parentNode.removeChild(b);if(a){a=a.previousSibling;var f=a.parentNode,c=a.nextSibling,e=0;do{if(c&&8===c.nodeType){var d=c.data;if("/$"===d)if(0===e)break;else e--;else"$"!==d&&"$?"!==d&&"$!"!==d||e++}d=c.nextSibling;f.removeChild(c);c=d}while(c);for(;b.firstChild;)f.insertBefore(b.firstChild,c);a.data="$";a._reactRetry&&a._reactRetry()}};$RC("');
q('$RC("');q('","');q('")\x3c/script>');q('function $RX(b,c,d,e){var a=document.getElementById(b);a&&(b=a.previousSibling,b.data="$!",a=a.dataset,c&&(a.dgst=c),d&&(a.msg=d),e&&(a.stck=e),b._reactRetry&&b._reactRetry())};$RX("');q('$RX("');q('"');q(")\x3c/script>");q(",");var E=null;
function F(a,b){if(a!==b){a.context._currentValue=a.parentValue;a=a.parent;var d=b.parent;if(null===a){if(null!==d)throw Error("The stacks must reach the root at the same time. This is a bug in React.");}else{if(null===d)throw Error("The stacks must reach the root at the same time. This is a bug in React.");F(a,d);b.context._currentValue=b.value}}}function ka(a){a.context._currentValue=a.parentValue;a=a.parent;null!==a&&ka(a)}
function la(a){var b=a.parent;null!==b&&la(b);a.context._currentValue=a.value}function ma(a,b){a.context._currentValue=a.parentValue;a=a.parent;if(null===a)throw Error("The depth must equal at least at zero before reaching the root. This is a bug in React.");a.depth===b.depth?F(a,b):ma(a,b)}
function na(a,b){var d=b.parent;if(null===d)throw Error("The depth must equal at least at zero before reaching the root. This is a bug in React.");a.depth===d.depth?F(a,d):na(a,d);b.context._currentValue=b.value}function G(a){var b=E;b!==a&&(null===b?la(a):null===a?ka(b):b.depth===a.depth?F(b,a):b.depth>a.depth?ma(b,a):na(b,a),E=a)}function oa(a,b){var d=a._currentValue;a._currentValue=b;var c=E;return E=a={parent:c,depth:null===c?0:c.depth+1,context:a,parentValue:d,value:b}}
function pa(a){switch(a.status){case "fulfilled":case "rejected":break;default:"string"!==typeof a.status&&(a.status="pending",a.then(function(b){"pending"===a.status&&(a.status="fulfilled",a.value=b)},function(b){"pending"===a.status&&(a.status="rejected",a.reason=b)}))}}var H=null,I=0,J=null;function qa(){var a=J;J=null;return a}function ra(a){return a._currentValue}
var wa={useMemo:function(a){return a()},useCallback:function(a){return a},useDebugValue:function(){},useDeferredValue:K,useTransition:K,getCacheForType:function(a){if(!L)throw Error("Reading the cache is only supported while rendering.");var b=L.get(a);void 0===b&&(b=a(),L.set(a,b));return b},readContext:ra,useContext:ra,useReducer:K,useRef:K,useState:K,useInsertionEffect:K,useLayoutEffect:K,useImperativeHandle:K,useEffect:K,useId:ta,useMutableSource:K,useSyncExternalStore:K,useCacheRefresh:function(){return ua},
useMemoCache:function(a){return Array(a)},use:va};function K(){throw Error("This Hook is not supported in Server Components.");}function ua(){if(!L)throw Error("Refreshing the cache is not supported in Server Components.");}var L=null;function ta(){if(null===H)throw Error("useId can only be used while React is rendering");var a=H.identifierCount++;return":"+H.identifierPrefix+"S"+a.toString(32)+":"}
function va(a){if(null!==a&&"object"===typeof a)if("function"===typeof a.then){var b=I;I+=1;switch(a.status){case "fulfilled":return a.value;case "rejected":throw a.reason;default:a:{if(null!==J){var d=J[b];if(void 0!==d)break a}d=null}if(null!==d)switch(d.status){case "fulfilled":return d.value;case "rejected":throw d.reason;default:throw d;}else throw null===J&&(J=[]),J[b]=a,a;}}else if(a.$$typeof===ca)return a._currentValue;throw Error("An unsupported type was passed to use(): "+String(a));}
var xa=e.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED,M=xa.ContextRegistry,N=xa.ReactCurrentDispatcher;function ya(a){console.error(a)}
function za(a,b,d,c,f){var g=new Set,h=[],k={status:0,fatalError:null,destination:null,bundlerConfig:b,cache:new Map,nextChunkId:0,pendingChunks:0,abortableTasks:g,pingedTasks:h,completedModuleChunks:[],completedJSONChunks:[],completedErrorChunks:[],writtenSymbols:new Map,writtenModules:new Map,writtenProviders:new Map,identifierPrefix:f||"",identifierCount:1,onError:void 0===d?ya:d,toJSON:function(a,b){return Aa(k,this,a,b)}};k.pendingChunks++;b=Ba(c);a=Ca(k,a,b,g);h.push(a);return k}var Da={};
function O(a,b,d,c,f){if(null!==d&&void 0!==d)throw Error("Refs cannot be used in server components, nor passed to client components.");if("function"===typeof a){if(a.$$typeof===w)return[x,a,b,c];I=0;J=f;return a(c)}if("string"===typeof a)return[x,a,b,c];if("symbol"===typeof a)return a===aa?c.children:[x,a,b,c];if(null!=a&&"object"===typeof a){if(a.$$typeof===w)return[x,a,b,c];switch(a.$$typeof){case y:var g=a._init;a=g(a._payload);return O(a,b,d,c,f);case da:return b=a.render,I=0,J=f,b(c,void 0);
case ea:return O(a.type,b,d,c,f);case ba:return oa(a._context,c.value),[x,a,b,{value:c.value,children:c.children,__pop:Da}]}}throw Error("Unsupported server component type: "+P(a));}function Ca(a,b,d,c){var f={id:a.nextChunkId++,status:0,model:b,context:d,ping:function(){var b=a.pingedTasks;b.push(f);1===b.length&&Ea(a)},thenableState:null};c.add(f);return f}
function Fa(a,b,d,c){var f=c.filepath+"#"+c.name+(c.async?"#async":""),g=a.writtenModules,h=g.get(f);if(void 0!==h)return b[0]===x&&"1"===d?"@"+h.toString(16):"$"+h.toString(16);try{var k=a.bundlerConfig[c.filepath][c.name];var r=c.async?{id:k.id,chunks:k.chunks,name:k.name,async:!0}:k;a.pendingChunks++;var A=a.nextChunkId++,S=u(r),T="M"+A.toString(16)+":"+S+"\n";var U=p.encode(T);a.completedModuleChunks.push(U);g.set(f,A);return b[0]===x&&"1"===d?"@"+A.toString(16):"$"+A.toString(16)}catch(V){return a.pendingChunks++,
b=a.nextChunkId++,d=Q(a,V),R(a,b,d),"$"+b.toString(16)}}function Ga(a){return Object.prototype.toString.call(a).replace(/^\[object (.*)\]$/,function(a,d){return d})}function W(a){var b=JSON.stringify(a);return'"'+a+'"'===b?a:b}function P(a){switch(typeof a){case "string":return JSON.stringify(10>=a.length?a:a.substr(0,10)+"...");case "object":if(ja(a))return"[...]";a=Ga(a);return"Object"===a?"{...}":a;case "function":return"function";default:return String(a)}}
function X(a,b){if(ja(a)){for(var d="[",c=0;c<a.length;c++){0<c&&(d+=", ");if(6<c){d+="...";break}var f=a[c];d=""+c===b&&"object"===typeof f&&null!==f?d+X(f):d+P(f)}return d+"]"}d="{";c=Object.keys(a);for(f=0;f<c.length;f++){0<f&&(d+=", ");if(6<f){d+="...";break}var g=c[f];d+=W(g)+": ";var h=a[g];d=g===b&&"object"===typeof h&&null!==h?d+X(h):d+P(h)}return d+"}"}
function Aa(a,b,d,c){switch(c){case x:return"$"}for(;"object"===typeof c&&null!==c&&(c.$$typeof===x||c.$$typeof===y);)try{switch(c.$$typeof){case x:var f=c;c=O(f.type,f.key,f.ref,f.props,null);break;case y:var g=c._init;c=g(c._payload)}}catch(h){if("object"===typeof h&&null!==h&&"function"===typeof h.then)return a.pendingChunks++,a=Ca(a,c,E,a.abortableTasks),c=a.ping,h.then(c,c),pa(h),a.thenableState=qa(),"@"+a.id.toString(16);Q(a,h);a.pendingChunks++;c=a.nextChunkId++;d=Q(a,h);R(a,c,d);return"@"+
c.toString(16)}if(null===c)return null;if("object"===typeof c){if(c.$$typeof===w)return Fa(a,b,d,c);if(c.$$typeof===ba)return f=c._context._globalName,b=a.writtenProviders,c=b.get(d),void 0===c&&(a.pendingChunks++,c=a.nextChunkId++,b.set(f,c),d="P"+c.toString(16)+":"+f+"\n",d=p.encode(d),a.completedJSONChunks.push(d)),"$"+c.toString(16);if(c===Da){a=E;if(null===a)throw Error("Tried to pop a Context at the root of the app. This is a bug in React.");c=a.parentValue;a.context._currentValue=c===fa?a.context._defaultValue:
c;E=a.parent;return}return c}if("string"===typeof c)return a="$"===c[0]||"@"===c[0]?"$"+c:c,a;if("boolean"===typeof c||"number"===typeof c||"undefined"===typeof c)return c;if("function"===typeof c){if(c.$$typeof===w)return Fa(a,b,d,c);if(/^on[A-Z]/.test(d))throw Error("Event handlers cannot be passed to client component props. Remove "+(W(d)+" from these props if possible: "+X(b)+"\nIf you need interactivity, consider converting part of this to a client component."));throw Error("Functions cannot be passed directly to client components because they're not serializable. Remove "+
(W(d)+" ("+(c.displayName||c.name||"function")+") from this object, or avoid the entire object: "+X(b)));}if("symbol"===typeof c){f=a.writtenSymbols;g=f.get(c);if(void 0!==g)return"$"+g.toString(16);g=c.description;if(Symbol.for(g)!==c)throw Error("Only global symbols received from Symbol.for(...) can be passed to client components. The symbol Symbol.for("+(c.description+") cannot be found among global symbols. Remove ")+(W(d)+" from this object, or avoid the entire object: "+X(b)));a.pendingChunks++;
d=a.nextChunkId++;b=u(g);b="S"+d.toString(16)+":"+b+"\n";b=p.encode(b);a.completedModuleChunks.push(b);f.set(c,d);return"$"+d.toString(16)}if("bigint"===typeof c)throw Error("BigInt ("+c+") is not yet supported in client component props. Remove "+(W(d)+" from this object or use a plain number instead: "+X(b)));throw Error("Type "+typeof c+" is not supported in client component props. Remove "+(W(d)+" from this object, or avoid the entire object: "+X(b)));}
function Q(a,b){a=a.onError;b=a(b);if(null!=b&&"string"!==typeof b)throw Error('onError returned something with a type other than "string". onError should return a string and may return null or undefined but must not return anything else. It received something of type "'+typeof b+'" instead');return b||""}function Y(a,b){null!==a.destination?(a.status=2,t(a.destination,b)):(a.status=1,a.fatalError=b)}
function R(a,b,d){d={digest:d};b="E"+b.toString(16)+":"+u(d)+"\n";b=p.encode(b);a.completedErrorChunks.push(b)}
function Ea(a){var b=N.current,d=L;N.current=wa;L=a.cache;H=a;try{var c=a.pingedTasks;a.pingedTasks=[];for(var f=0;f<c.length;f++){var g=c[f];var h=a;if(0===g.status){G(g.context);try{var k=g.model;if("object"===typeof k&&null!==k&&k.$$typeof===x){var r=k,A=g.thenableState;g.model=k;k=O(r.type,r.key,r.ref,r.props,A);for(g.thenableState=null;"object"===typeof k&&null!==k&&k.$$typeof===x;)r=k,g.model=k,k=O(r.type,r.key,r.ref,r.props,null)}var S=g.id,T=u(k,h.toJSON),U="J"+S.toString(16)+":"+T+"\n";var V=
p.encode(U);h.completedJSONChunks.push(V);h.abortableTasks.delete(g);g.status=1}catch(v){if("object"===typeof v&&null!==v&&"function"===typeof v.then){var sa=g.ping;v.then(sa,sa);pa(v);g.thenableState=qa()}else{h.abortableTasks.delete(g);g.status=4;var Ia=Q(h,v);R(h,g.id,Ia)}}}}null!==a.destination&&Z(a,a.destination)}catch(v){Q(a,v),Y(a,v)}finally{N.current=b,L=d,H=null}}
function Z(a,b){l=new Uint8Array(512);m=0;try{for(var d=a.completedModuleChunks,c=0;c<d.length;c++)if(a.pendingChunks--,!n(b,d[c])){a.destination=null;c++;break}d.splice(0,c);var f=a.completedJSONChunks;for(c=0;c<f.length;c++)if(a.pendingChunks--,!n(b,f[c])){a.destination=null;c++;break}f.splice(0,c);var g=a.completedErrorChunks;for(c=0;c<g.length;c++)if(a.pendingChunks--,!n(b,g[c])){a.destination=null;c++;break}g.splice(0,c)}finally{l&&0<m&&(b.enqueue(new Uint8Array(l.buffer,0,m)),l=null,m=0)}0===
a.pendingChunks&&b.close()}function Ha(a,b){try{var d=a.abortableTasks;if(0<d.size){var c=Q(a,void 0===b?Error("The render was aborted by the server without a reason."):b);a.pendingChunks++;var f=a.nextChunkId++;R(a,f,c);d.forEach(function(b){b.status=3;var c="$"+f.toString(16);b=b.id;c=u(c);c="J"+b.toString(16)+":"+c+"\n";c=p.encode(c);a.completedErrorChunks.push(c)});d.clear()}null!==a.destination&&Z(a,a.destination)}catch(g){Q(a,g),Y(a,g)}}
function Ba(a){if(a){var b=E;G(null);for(var d=0;d<a.length;d++){var c=a[d],f=c[0];c=c[1];M[f]||(M[f]=e.createServerContext(f,fa));oa(M[f],c)}a=E;G(b);return a}return null}
exports.renderToReadableStream=function(a,b,d){var c=za(a,b,d?d.onError:void 0,d?d.context:void 0,d?d.identifierPrefix:void 0);if(d&&d.signal){var f=d.signal;if(f.aborted)Ha(c,f.reason);else{var g=function(){Ha(c,f.reason);f.removeEventListener("abort",g)};f.addEventListener("abort",g)}}return new ReadableStream({type:"bytes",start:function(){Ea(c)},pull:function(a){if(1===c.status)c.status=2,t(a,c.fatalError);else if(2!==c.status&&null===c.destination){c.destination=a;try{Z(c,a)}catch(k){Q(c,k),
Y(c,k)}}},cancel:function(){}},{highWaterMark:0})};
