[package]
name = "turbopack-swc-utils"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
parking_lot = { workspace = true }
turbo-rcstr = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }

swc_core = { workspace = true, features = [
  "base",
  "common",
  "common_concurrent",
  "common_sourcemap",
] }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime", "turbopack-core/tokio_runtime"]
sync = ["turbo-tasks/sync", "turbopack-core/sync"]

