[package]
name = "turbopack-cli-utils"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
crossterm = "0.26.0"
owo-colors = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }
turbo-rcstr = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }
turbo-tasks-fs = { path = "../turbo-tasks-fs", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }
turbopack-resolve = { path = "../turbopack-resolve", default-features = false }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime", "turbo-tasks-fs/tokio_runtime", "turbopack-core/tokio_runtime", "turbopack-resolve/tokio_runtime"]
sync = ["turbo-tasks/sync", "turbo-tasks-fs/sync", "turbopack-core/sync", "turbopack-resolve/sync"]

