name: 'Auto pull request'
on:
  push:
    branches:
      - canary
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          title: 'Auto PR from ${{ github.ref_name }}'
          body: 'This PR was automatically created by Github Actions.'