name: Allow issue participants to reopen issues

on:
  issues:
    types: [closed]
  issue_comment:
    types: [created]

permissions: {}

concurrency:
  group: issue-reopen-${{ github.event.issue.number }}
  cancel-in-progress: false
  queue: max

jobs:
  handle:
    name: Handle issue reopening
    if: >-
      github.event.issue.pull_request == null &&
      (
        github.event_name == 'issues' ||
        (
          github.event.issue.state == 'closed' &&
          github.event.comment.user.type == 'User'
        )
      )
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Handle issue closure or reopening request
        uses: vercel/next.js/.github/actions/issue-reopen@canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
