name: Allow issue participants to reopen issues

on:
  issues:
    types: [closed]
  issue_comment:
    types: [created]

permissions: {}

concurrency:
  group: issue-reopen-${{ github.event.issue.number }}
  cancel-in-progress: false
  queue: max

jobs:
  handle:
    name: Handle issue reopening
    if: >-
      github.event.issue.pull_request == null &&
      (
        github.event_name == 'issues' ||
        (
          github.event.issue.state == 'closed' &&
          github.event.comment.user.type == 'User'
        )
      )
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout local action
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          sparse-checkout: .github/actions/issue-reopen

      - name: Handle issue closure or reopening request
        uses: ./.github/actions/issue-reopen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
