name: Generate Stats
on:
  pull_request: {}
permissions:
  contents: read
jobs:
  aggregate-stats:
    name: aggregate stats (poc)
    runs-on: ubuntu-latest
    steps:
      - name: job logs
        run: |
          echo '--stats start--'
          echo '<!-- __NEXT_STATS_COMMENT__ -->'
          echo ''
          echo ''
          echo '--stats end--'
      - name: pr-ci-metadata artifact
        run: |
          mkdir -p pr-ci-metadata
          cat > pr-ci-metadata/pr.json <<'JSON'
{
  "number": 91587,
  "headSha": "bc14dae1815bf6a74de6b1d50ced9f4a7f7901bc",
  "headRef": "poc-pr-ci-metadata",
  "headRepo": "vercel/next.js",
  "baseRef": "canary"
}
JSON
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-ci-metadata
          path: pr-ci-metadata

129789