name: Spelling

permissions:
  contents: read

on:
  push:
    branches: ['canary']
  pull_request:
    types: [opened, synchronize]

env:
  CLICOLOR: 1

jobs:
  spelling:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.34.0
