name: test-gh-update-next-workflow-trigger

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - '.github/workflows/test_e2e_deploy_release.yml'
      - '.github/workflows/test_gh_update_next_workflow_trigger.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  token-smoke-test:
    name: Token Smoke Test
    if: ${{ github.repository_owner == 'vercel' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check token
        run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GH_UPDATE_NEXT_WORKFLOW_TRIGGER }}
