on:
  schedule:
    # run every day at 23:15
    - cron: '15 23 * * *'

  workflow_dispatch:
    inputs:
      releaseType:
        description: stable, canary, beta, or release candidate?
        required: true
        type: choice
        options:
          - canary
          - stable
          - release-candidate
          - beta

      semverType:
        description: semver type?
        type: choice
        options:
          - patch
          - minor
          - major

      force:
        description: create a new release even if there are no new commits
        default: false
        type: boolean

name: Trigger Release

env:
  NAPI_CLI_VERSION: 2.18.4
  TURBO_VERSION: 2.8.11
  NODE_LTS_VERSION: 20

permissions:
  contents: write # for creating the release tag
  id-token: write # for creating the GitHub App token

jobs:
  start:
    if: github.repository_owner == 'vercel'
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: 1
      # we build a dev binary for use in CI so skip downloading
      # canary next-swc binaries in the monorepo
      NEXT_SKIP_NATIVE_POSTINSTALL: 1

    steps:
      - name: Create GitHub App token
        id: release-app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.RELEASE_GITHUB_APP_CLIENT_ID }}
          private-key: ${{ secrets.RELEASE_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: next.js
          permission-contents: write

      - name: Create hardcoded release tag
        run: |
          curl --fail-with-body --include -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${RELEASE_GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            -H "Content-Type: application/json" \
            "https://api.github.com/repos/vercel/next.js/git/refs" \
            -d @- <<EOF
          {
            "ref": "refs/heads/sebbie/debug-ref-creation",
            "sha": "${RELEASE_SHA}"
          }
          EOF
        env:
          RELEASE_GITHUB_TOKEN: ${{ steps.release-app-token.outputs.token }}
          RELEASE_SHA: ${{ github.sha }}