name: Webpack Next.js development integration tests

on:
  schedule:
    # Run an hour earlier than the rspack tests, so we don't overwhelm the CI
    - cron: '0 4 * * *'
  workflow_dispatch: {}

jobs:
  test-dev:
    name: Webpack integration tests
    uses: ./.github/workflows/integration_tests_reusable.yml
    with:
      name: webpack-development
      test_type: development
      run_before_test: |
        export IS_WEBPACK_TEST=1
    secrets: inherit
