;[
  'test/unit/yarn-workspace-esm/input.js',
  'test/unit/yarn-workspace-esm/node_modules/@example/common',
  'test/unit/yarn-workspace-esm/node_modules/@example/web',
  'test/unit/yarn-workspace-esm/package.json',
  'test/unit/yarn-workspace-esm/packages/common/hello.js',
  'test/unit/yarn-workspace-esm/packages/common/package.json',
  'test/unit/yarn-workspace-esm/packages/web/index.js',
  'test/unit/yarn-workspace-esm/packages/web/package.json',
]
