[package]
name = "turbopack-env"
version = "0.1.0"
description = "TBD"
license = "MIT"
edition = "2024"
autobenches = false

[lib]
bench = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
turbo-rcstr = { workspace = true }
turbo-tasks = { path = "../turbo-tasks", default-features = false }
turbo-tasks-env = { path = "../turbo-tasks-env", default-features = false }
turbo-tasks-fs = { path = "../turbo-tasks-fs", default-features = false }
turbopack-core = { path = "../turbopack-core", default-features = false }
turbopack-ecmascript = { path = "../turbopack-ecmascript", default-features = false }

[features]
default = ["tokio_runtime"]
tokio_runtime = ["turbo-tasks/tokio_runtime", "turbo-tasks-env/tokio_runtime", "turbo-tasks-fs/tokio_runtime", "turbopack-core/tokio_runtime", "turbopack-ecmascript/tokio_runtime"]
sync = ["turbo-tasks/sync", "turbo-tasks-env/sync", "turbo-tasks-fs/sync", "turbopack-core/sync", "turbopack-ecmascript/sync"]

